[tool.poetry]
name = "advisor"
packages = [{include = "agent"}]
version = "0.1.0"
description = ""
authors = ["r1char9"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain-mistralai = "^0.2.0"
pytest = "^8.3.3"
langchain-community = "^0.3.2"
qdrant-client = {version = ">=1.8.2", extras = ["fastembed"]}
langchain = "^0.3.3"
fake-useragent = "^1.5.1"
langchain-huggingface = "^0.1.2"
bs4 = "^0.0.2"
lxml = "^5.3.0"
langgraph = "^0.2.46"
pandas = "^2.2.3"
langchain-ollama = "^0.2.0"
mteb = "^1.19.6"
aiofiles = "^24.1.0"
asyncio = "^3.4.3"
pymilvus = {extras = ["model"], version = "^2.4.9"}
faiss-cpu = "^1.9.0.post1"
nltk = "^3.9.1"
ranx = "^0.3.20"
fastapi = "^0.115.6"
vllm = "^0.6.4.post1"
openai = "^1.56.2"
paramiko = "^3.5.0"
sshtunnel = "^0.4.0"
python-multipart = "^0.0.20"
tools = "^0.1.9"
fitz = "^0.0.1.dev2"
python-docx = "^1.1.2"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
